---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/services":
    get:
      summary: Retrieves a cars
      tags:
      - Cars
      responses:
        '200':
          description: cars list
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  image:
                    type: string
                  price:
                    type: string
                  details:
                    type: string
                required:
                - id
                - name
                - image
                - details
                - price
        '404':
          description: Car not found
        '406':
          description: unsupported accept header
  "/api/services/{id}":
    get:
      summary: Retrieves a car
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Car
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  image:
                    type: string
                  price:
                    type: string
                  details:
                    type: string
                required:
                - id
                - name
                - image
                - details
                - price
        '404':
          description: Car not found
        '406':
          description: unsupported accept header
    delete:
      summary: Delete a car
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Car
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: Deleted
        '404':
          description: Car not found
        '406':
          description: unsupported accept header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:4000
